//AUTOGENERATED - DO NOT TOUCH!
public struct InputAction {
    public const int DirX = 0;
    public const int DirY = 1;
    public const int Special = 2;
    public const int Menu = 3;
    public const int Jump = 4;
    public const int Hook = 5;
    public const int MenuAccept = 6;
}
